version: '2.17'
services:
  db:
    image: zhmeshneck/postgres:v0.1
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
  bot:
    image: zhmeshneck/fyr:v0.2
    command: sh -c "make migrate && python3.9 bot"
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db

volumes:
  pgdata: